#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rezervacijo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RezervacijosDB")]
	public partial class DuomenysDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertLektuva(Lektuva instance);
    partial void UpdateLektuva(Lektuva instance);
    partial void DeleteLektuva(Lektuva instance);
    partial void InsertVieta(Vieta instance);
    partial void UpdateVieta(Vieta instance);
    partial void DeleteVieta(Vieta instance);
    #endregion
		
		public DuomenysDataContext() : 
				base(global::Rezervacijo.Properties.Settings.Default.RezervacijosDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DuomenysDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DuomenysDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DuomenysDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DuomenysDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<Lektuva> Lektuvas
		{
			get
			{
				return this.GetTable<Lektuva>();
			}
		}
		
		public System.Data.Linq.Table<Vieta> Vietas
		{
			get
			{
				return this.GetTable<Vieta>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Vardas;
		
		private string _Pavarde;
		
		private string _UserName;
		
		private string _Password;
		
		private EntitySet<Vieta> _Vietas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnVardasChanging(string value);
    partial void OnVardasChanged();
    partial void OnPavardeChanging(string value);
    partial void OnPavardeChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
		
		public User()
		{
			this._Vietas = new EntitySet<Vieta>(new Action<Vieta>(this.attach_Vietas), new Action<Vieta>(this.detach_Vietas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vardas", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Vardas
		{
			get
			{
				return this._Vardas;
			}
			set
			{
				if ((this._Vardas != value))
				{
					this.OnVardasChanging(value);
					this.SendPropertyChanging();
					this._Vardas = value;
					this.SendPropertyChanged("Vardas");
					this.OnVardasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pavarde", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Pavarde
		{
			get
			{
				return this._Pavarde;
			}
			set
			{
				if ((this._Pavarde != value))
				{
					this.OnPavardeChanging(value);
					this.SendPropertyChanging();
					this._Pavarde = value;
					this.SendPropertyChanged("Pavarde");
					this.OnPavardeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Vieta", Storage="_Vietas", ThisKey="Id", OtherKey="UserID")]
		public EntitySet<Vieta> Vietas
		{
			get
			{
				return this._Vietas;
			}
			set
			{
				this._Vietas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Vietas(Vieta entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_Vietas(Vieta entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lektuvas")]
	public partial class Lektuva : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.DateTime _Isvykimas;
		
		private string _AtvykimoVieta;
		
		private int _PirmosKlasesVietuSkaicius;
		
		private int _AntrosKlasesVietuSkaicius;
		
		private EntitySet<Vieta> _Vietas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIsvykimasChanging(System.DateTime value);
    partial void OnIsvykimasChanged();
    partial void OnAtvykimoVietaChanging(string value);
    partial void OnAtvykimoVietaChanged();
    partial void OnPirmosKlasesVietuSkaiciusChanging(int value);
    partial void OnPirmosKlasesVietuSkaiciusChanged();
    partial void OnAntrosKlasesVietuSkaiciusChanging(int value);
    partial void OnAntrosKlasesVietuSkaiciusChanged();
    #endregion
		
		public Lektuva()
		{
			this._Vietas = new EntitySet<Vieta>(new Action<Vieta>(this.attach_Vietas), new Action<Vieta>(this.detach_Vietas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Isvykimas", DbType="DateTime NOT NULL")]
		public System.DateTime Isvykimas
		{
			get
			{
				return this._Isvykimas;
			}
			set
			{
				if ((this._Isvykimas != value))
				{
					this.OnIsvykimasChanging(value);
					this.SendPropertyChanging();
					this._Isvykimas = value;
					this.SendPropertyChanged("Isvykimas");
					this.OnIsvykimasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AtvykimoVieta", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string AtvykimoVieta
		{
			get
			{
				return this._AtvykimoVieta;
			}
			set
			{
				if ((this._AtvykimoVieta != value))
				{
					this.OnAtvykimoVietaChanging(value);
					this.SendPropertyChanging();
					this._AtvykimoVieta = value;
					this.SendPropertyChanged("AtvykimoVieta");
					this.OnAtvykimoVietaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PirmosKlasesVietuSkaicius", DbType="Int NOT NULL")]
		public int PirmosKlasesVietuSkaicius
		{
			get
			{
				return this._PirmosKlasesVietuSkaicius;
			}
			set
			{
				if ((this._PirmosKlasesVietuSkaicius != value))
				{
					this.OnPirmosKlasesVietuSkaiciusChanging(value);
					this.SendPropertyChanging();
					this._PirmosKlasesVietuSkaicius = value;
					this.SendPropertyChanged("PirmosKlasesVietuSkaicius");
					this.OnPirmosKlasesVietuSkaiciusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AntrosKlasesVietuSkaicius", DbType="Int NOT NULL")]
		public int AntrosKlasesVietuSkaicius
		{
			get
			{
				return this._AntrosKlasesVietuSkaicius;
			}
			set
			{
				if ((this._AntrosKlasesVietuSkaicius != value))
				{
					this.OnAntrosKlasesVietuSkaiciusChanging(value);
					this.SendPropertyChanging();
					this._AntrosKlasesVietuSkaicius = value;
					this.SendPropertyChanged("AntrosKlasesVietuSkaicius");
					this.OnAntrosKlasesVietuSkaiciusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lektuva_Vieta", Storage="_Vietas", ThisKey="Id", OtherKey="PlaneID")]
		public EntitySet<Vieta> Vietas
		{
			get
			{
				return this._Vietas;
			}
			set
			{
				this._Vietas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Vietas(Vieta entity)
		{
			this.SendPropertyChanging();
			entity.Lektuva = this;
		}
		
		private void detach_Vietas(Vieta entity)
		{
			this.SendPropertyChanging();
			entity.Lektuva = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vieta")]
	public partial class Vieta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private bool _firstclass;
		
		private System.Nullable<int> _eile;
		
		private System.Nullable<int> _number;
		
		private int _UserID;
		
		private int _PlaneID;
		
		private EntityRef<Lektuva> _Lektuva;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnfirstclassChanging(bool value);
    partial void OnfirstclassChanged();
    partial void OneileChanging(System.Nullable<int> value);
    partial void OneileChanged();
    partial void OnnumberChanging(System.Nullable<int> value);
    partial void OnnumberChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnPlaneIDChanging(int value);
    partial void OnPlaneIDChanged();
    #endregion
		
		public Vieta()
		{
			this._Lektuva = default(EntityRef<Lektuva>);
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstclass", DbType="Bit NOT NULL")]
		public bool firstclass
		{
			get
			{
				return this._firstclass;
			}
			set
			{
				if ((this._firstclass != value))
				{
					this.OnfirstclassChanging(value);
					this.SendPropertyChanging();
					this._firstclass = value;
					this.SendPropertyChanged("firstclass");
					this.OnfirstclassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eile", DbType="Int")]
		public System.Nullable<int> eile
		{
			get
			{
				return this._eile;
			}
			set
			{
				if ((this._eile != value))
				{
					this.OneileChanging(value);
					this.SendPropertyChanging();
					this._eile = value;
					this.SendPropertyChanged("eile");
					this.OneileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number", DbType="Int")]
		public System.Nullable<int> number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this.OnnumberChanging(value);
					this.SendPropertyChanging();
					this._number = value;
					this.SendPropertyChanged("number");
					this.OnnumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlaneID", DbType="Int NOT NULL")]
		public int PlaneID
		{
			get
			{
				return this._PlaneID;
			}
			set
			{
				if ((this._PlaneID != value))
				{
					if (this._Lektuva.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPlaneIDChanging(value);
					this.SendPropertyChanging();
					this._PlaneID = value;
					this.SendPropertyChanged("PlaneID");
					this.OnPlaneIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lektuva_Vieta", Storage="_Lektuva", ThisKey="PlaneID", OtherKey="Id", IsForeignKey=true)]
		public Lektuva Lektuva
		{
			get
			{
				return this._Lektuva.Entity;
			}
			set
			{
				Lektuva previousValue = this._Lektuva.Entity;
				if (((previousValue != value) 
							|| (this._Lektuva.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Lektuva.Entity = null;
						previousValue.Vietas.Remove(this);
					}
					this._Lektuva.Entity = value;
					if ((value != null))
					{
						value.Vietas.Add(this);
						this._PlaneID = value.Id;
					}
					else
					{
						this._PlaneID = default(int);
					}
					this.SendPropertyChanged("Lektuva");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Vieta", Storage="_User", ThisKey="UserID", OtherKey="Id", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.Vietas.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.Vietas.Add(this);
						this._UserID = value.Id;
					}
					else
					{
						this._UserID = default(int);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
